---
name:             InventoryMonitor
main:             presentkim\inventorymonitor\InventoryMonitor
version:          1.0.5
api:              [3.0.0-ALPHA12]
author:           PresentKim
website:          https://github.com/PMMPPlugin/InventoryMonitor
description:      A plugin show other player's inventory

permissions:
  inventorymonitor.cmd:
    description:  "Open player's inventory"
    default:      op
...
