---
name:             InventoryMonitor
main:             blugin\inventorymonitor\InventoryMonitor
version:          1.0.6
api:              [3.0.0-ALPHA12]
author:           PresentKim
website:          https://github.com/Blugin/InventoryMonitor-PMMP
description:      A plugin monitoring player's inventory

permissions:
  inventorymonitor.cmd:
    description:  "Open player's inventory"
    default:      op
...
