---
name: InventoryMonitor
main: blugin\inventorymonitor\InventoryMonitor
version: 1.0.8
api: [3.0.0-ALPHA12]
author: PresentKim
website: https://github.com/Blugin/InventoryMonitor-PMMP
description: Monitoring player inventory

permissions:
  inventorymonitor.cmd:
    description: Open player inventory
    default: op
...